### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by white8785** [elfbread/pyAirports#1]
# Readme
* Instead of listing the names of the add-ons, provide the actual package name like `pip install pandas` or drop the packages in a `requirements.txt` file and allow the user to `pip install -r requirements.txt` instead.
* ordered and non-ordered lists are your friend.  Use them to make the following process steps easier on the eyes
* `matplotlib` missing from your requirements

**Comment by elfbread** [comment]
I think I've addressed these comments. Please take a look if you get the chance. I won't be in class next week for more review.

**Comment by white8785** [comment]
Last check-in.  Nice adjustment, but you're requirements.txt file is empty.  The packages should be listed in there so pip installs them.

**Comment by elfbread** [comment]
Wow, not sure how that even happened! Thank you!
